### ISSUE TITLE
Quasar http navigation error happens to some tv shows

### ISSUE THREAD

**Issue by dtsexpert** [metate/official-meta-players#1]
I get Quasar http navigation error for some tv show (*******)
Testing same shows in Quasar works fine.
Attatched is kodi logs
Once again thanks so much for your great addon
[kodilogs.txt](https://github.com/metate/official-meta-players/files/164976/kodilogs.txt)

**Comment by metate** [comment]
Are you sure it works fine with Quasar itself?
For me Quasar crash on these with the same error even when I just list the episodes of some of the seasons within Quasar (no playback attempt). Seems like a bug in Quasar. http://pastebin.com/ngpr6WQv

EDIT: with latest quasar it does list the episodes but most of them, including the one you tried, are not listed at all. Unfortunately since the data is missing in TMDB there is nothing I can do. The community need to add the information to TMDB. Quasar switched from TVDB to TMDB 18 days ago and the developer says he won't change it back. See https://github.com/scakemyer/plugin.video.quasar/issues/249#issuecomment-186682080
